"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Loader2 } from "lucide-react";
import { ProgressPreviewTree } from "./progress-preview-tree";
import {
  getReportTemplates,
  getProjects,
  getSubProjects,
  getProgressLogs,
  createReport,
} from "@/lib/actions/reports";
import type {
  ReportTemplate,
  Project,
  SubProject,
  ProgressLogWithDetails,
  ReportContent,
  ReportContentMatrix,
  ReportContentList,
  ReportContentLogEntry,
  ReportSectionContent,
} from "@/types/database";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onGenerated: (reportId: string) => void;
}

function getMonday(date: Date): Date {
  const d = new Date(date);
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  d.setDate(diff);
  return d;
}

function getSunday(date: Date): Date {
  const monday = getMonday(date);
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  return sunday;
}

function getFirstOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), 1);
}

function getLastOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth() + 1, 0);
}

function toDateString(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  onGenerated,
}: AutoGenerateDialogProps) {
  // Step 1: Template & Project selection
  const [templates, setTemplates] = useState<ReportTemplate[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>("");
  const [selectedProjectId, setSelectedProjectId] = useState<string>("");
  const [periodStart, setPeriodStart] = useState<string>("");
  const [periodEnd, setPeriodEnd] = useState<string>("");

  // Step 2: Progress preview
  const [subProjects, setSubProjects] = useState<SubProject[]>([]);
  const [progressLogs, setProgressLogs] = useState<ProgressLogWithDetails[]>([]);
  const [checkedLogIds, setCheckedLogIds] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(false);
  const [fetchingLogs, setFetchingLogs] = useState(false);

  // Step 3: Additional options
  const [includeNextPeriodPlans, setIncludeNextPeriodPlans] = useState(true);
  const [includeMeetings, setIncludeMeetings] = useState(true);

  const selectedTemplate = useMemo(
    () => templates.find((t) => t.id === selectedTemplateId) ?? null,
    [templates, selectedTemplateId]
  );

  // Load templates and projects on open
  useEffect(() => {
    if (!open) return;
    let cancelled = false;

    async function loadInitialData() {
      const [templatesResult, projectsResult] = await Promise.all([
        getReportTemplates(),
        getProjects(),
      ]);

      if (cancelled) return;

      if (templatesResult.data) {
        setTemplates(templatesResult.data as ReportTemplate[]);
      }
      if (projectsResult.data) {
        setProjects(projectsResult.data as Project[]);
      }
    }

    loadInitialData();
    return () => { cancelled = true; };
  }, [open]);

  // Auto-select project when template has project_id
  useEffect(() => {
    if (selectedTemplate?.project_id) {
      setSelectedProjectId(selectedTemplate.project_id);
    }
  }, [selectedTemplate]);

  // Fetch sub_projects when project changes
  useEffect(() => {
    if (!selectedProjectId) {
      setSubProjects([]);
      return;
    }
    let cancelled = false;

    async function loadSubProjects() {
      const result = await getSubProjects(selectedProjectId);
      if (cancelled) return;
      if (result.data) {
        setSubProjects(result.data as SubProject[]);
      }
    }

    loadSubProjects();
    return () => { cancelled = true; };
  }, [selectedProjectId]);

  // Auto-fetch progress logs when all required fields set
  useEffect(() => {
    if (!selectedProjectId || !periodStart || !periodEnd) {
      setProgressLogs([]);
      setCheckedLogIds(new Set());
      return;
    }
    let cancelled = false;

    async function fetchLogs() {
      setFetchingLogs(true);
      try {
        const result = await getProgressLogs({
          projectId: selectedProjectId,
          startDate: periodStart,
          endDate: periodEnd,
        });
        if (cancelled) return;
        if (result.data) {
          const logs = result.data as ProgressLogWithDetails[];
          setProgressLogs(logs);
          // Default: all logs checked
          setCheckedLogIds(new Set(logs.map((l) => l.id)));
        }
      } catch (err) {
        console.error("Failed to fetch progress logs:", err);
      } finally {
        if (!cancelled) setFetchingLogs(false);
      }
    }

    fetchLogs();
    return () => { cancelled = true; };
  }, [selectedProjectId, periodStart, periodEnd]);

  const handleToggleLog = useCallback((logId: string) => {
    setCheckedLogIds((prev) => {
      const next = new Set(prev);
      if (next.has(logId)) {
        next.delete(logId);
      } else {
        next.add(logId);
      }
      return next;
    });
  }, []);

  const handleToggleSubProject = useCallback(
    (subProjectId: string) => {
      const logsInSubProject = progressLogs.filter(
        (l) => l.sub_project_id === subProjectId
      );
      const allChecked = logsInSubProject.every((l) => checkedLogIds.has(l.id));

      setCheckedLogIds((prev) => {
        const next = new Set(prev);
        for (const log of logsInSubProject) {
          if (allChecked) {
            next.delete(log.id);
          } else {
            next.add(log.id);
          }
        }
        return next;
      });
    },
    [progressLogs, checkedLogIds]
  );

  const handleSetThisWeek = useCallback(() => {
    const now = new Date();
    setPeriodStart(toDateString(getMonday(now)));
    setPeriodEnd(toDateString(getSunday(now)));
  }, []);

  const handleSetThisMonth = useCallback(() => {
    const now = new Date();
    setPeriodStart(toDateString(getFirstOfMonth(now)));
    setPeriodEnd(toDateString(getLastOfMonth(now)));
  }, []);

  const buildReportContent = useCallback((): ReportContent => {
    if (!selectedTemplate) return {};

    const checkedLogs = progressLogs.filter((l) => checkedLogIds.has(l.id));
    const content: ReportContent = {};

    for (const section of selectedTemplate.sections) {
      if (section.type === "progress_matrix") {
        const matrix: ReportContentMatrix = {};

        for (const sp of subProjects) {
          const spLogs = checkedLogs.filter(
            (l) => l.sub_project_id === sp.id
          );

          if (section.columns) {
            const cell: Record<string, ReportContentLogEntry[]> = {};
            for (const col of section.columns) {
              // Match logs to columns based on auto_fill config
              const matchingLogs = spLogs.filter((log) => {
                if (!section.auto_fill) return true;
                const statusMatch =
                  !section.auto_fill.status ||
                  section.auto_fill.status.includes(log.status);
                const typeMatch =
                  !section.auto_fill.log_type ||
                  section.auto_fill.log_type.includes(log.log_type);
                // Map column key to status
                if (col.key === "completed" || col.key === "progress") {
                  return (
                    (log.status === "completed" || log.status === "in_progress") &&
                    typeMatch
                  );
                }
                if (col.key === "planned" || col.key === "plan") {
                  return log.status === "planned" && typeMatch;
                }
                return statusMatch && typeMatch;
              });

              cell[col.key] = matchingLogs.map((log) => ({
                log_id: log.id,
                text: log.title,
              }));
            }
            matrix[sp.id] = cell;
          }
        }

        content[section.id] = matrix as ReportSectionContent;
      } else if (section.type === "list") {
        const filteredLogs = checkedLogs.filter((log) => {
          if (!section.auto_fill) return true;
          const typeMatch =
            !section.auto_fill.log_type ||
            section.auto_fill.log_type.includes(log.log_type);
          const statusMatch =
            !section.auto_fill.status ||
            section.auto_fill.status.includes(log.status);
          return typeMatch && statusMatch;
        });

        const listContent: ReportContentList = {
          items: filteredLogs.map((log) => ({
            log_id: log.id,
            text: log.title,
          })),
        };
        content[section.id] = listContent as ReportSectionContent;
      } else if (section.type === "text") {
        content[section.id] = { text: "" } as ReportSectionContent;
      }
    }

    return content;
  }, [selectedTemplate, progressLogs, checkedLogIds, subProjects]);

  const handleGenerate = useCallback(async () => {
    if (!selectedTemplate || !periodStart || !periodEnd) return;

    setLoading(true);
    try {
      const content = buildReportContent();
      const selectedProject = projects.find((p) => p.id === selectedProjectId);
      const title = `${selectedTemplate.name} (${periodStart} ~ ${periodEnd})${
        selectedProject ? ` - ${selectedProject.short_name ?? selectedProject.name}` : ""
      }`;

      const result = await createReport({
        templateId: selectedTemplate.id,
        projectId: selectedProjectId || undefined,
        title,
        periodStart,
        periodEnd,
        content,
      });

      if (result.error) {
        console.error("Failed to create report:", result.error);
        return;
      }

      if (result.id) {
        onGenerated(result.id);
        onOpenChange(false);
        resetState();
      }
    } catch (err) {
      console.error("Failed to generate report:", err);
    } finally {
      setLoading(false);
    }
  }, [
    selectedTemplate,
    selectedProjectId,
    periodStart,
    periodEnd,
    projects,
    buildReportContent,
    onGenerated,
    onOpenChange,
  ]);

  const resetState = useCallback(() => {
    setSelectedTemplateId("");
    setSelectedProjectId("");
    setPeriodStart("");
    setPeriodEnd("");
    setProgressLogs([]);
    setCheckedLogIds(new Set());
    setSubProjects([]);
    setIncludeNextPeriodPlans(true);
    setIncludeMeetings(true);
  }, []);

  const canGenerate =
    selectedTemplateId && periodStart && periodEnd && !loading;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>보고서 자동 생성</DialogTitle>
          <DialogDescription>
            양식과 기간을 선택하면 추진경과를 자동으로 불러옵니다.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5">
          {/* 양식 선택 */}
          <div className="space-y-2">
            <Label>양식 선택</Label>
            <Select
              value={selectedTemplateId}
              onValueChange={setSelectedTemplateId}
            >
              <SelectTrigger>
                <SelectValue placeholder="보고서 양식을 선택하세요" />
              </SelectTrigger>
              <SelectContent>
                {templates.map((t) => (
                  <SelectItem key={t.id} value={t.id}>
                    {t.name}
                    {t.description ? ` - ${t.description}` : ""}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* 프로젝트 선택 */}
          <div className="space-y-2">
            <Label>프로젝트</Label>
            <Select
              value={selectedProjectId}
              onValueChange={setSelectedProjectId}
              disabled={!!selectedTemplate?.project_id}
            >
              <SelectTrigger>
                <SelectValue placeholder="프로젝트를 선택하세요" />
              </SelectTrigger>
              <SelectContent>
                {projects.map((p) => (
                  <SelectItem key={p.id} value={p.id}>
                    [{p.code}] {p.short_name ?? p.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {selectedTemplate?.project_id && (
              <p className="text-xs text-muted-foreground">
                양식에 연결된 프로젝트가 자동 선택되었습니다.
              </p>
            )}
          </div>

          {/* 기간 설정 */}
          <div className="space-y-2">
            <Label>기간 설정</Label>
            <div className="flex items-center gap-2">
              <Input
                type="date"
                value={periodStart}
                onChange={(e) => setPeriodStart(e.target.value)}
                className="flex-1"
              />
              <span className="text-muted-foreground shrink-0">~</span>
              <Input
                type="date"
                value={periodEnd}
                onChange={(e) => setPeriodEnd(e.target.value)}
                className="flex-1"
              />
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleSetThisWeek}
              >
                금주
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleSetThisMonth}
              >
                이번달
              </Button>
            </div>
          </div>

          {/* 추진경과 미리보기 */}
          {(progressLogs.length > 0 || fetchingLogs) && (
            <div className="space-y-2">
              <Label>추진경과 미리보기</Label>
              {fetchingLogs ? (
                <div className="flex items-center justify-center py-6">
                  <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                  <span className="ml-2 text-sm text-muted-foreground">
                    추진경과를 불러오는 중...
                  </span>
                </div>
              ) : (
                <div className="border rounded-md p-3 max-h-64 overflow-y-auto">
                  <ProgressPreviewTree
                    subProjects={subProjects}
                    progressLogs={progressLogs}
                    checkedLogIds={checkedLogIds}
                    onToggleLog={handleToggleLog}
                    onToggleSubProject={handleToggleSubProject}
                  />
                </div>
              )}
            </div>
          )}

          {/* 선택 완료 안내 (로그가 없고 fetching도 아닌데 조건은 충족된 경우) */}
          {!fetchingLogs &&
            progressLogs.length === 0 &&
            selectedProjectId &&
            periodStart &&
            periodEnd && (
              <div className="border rounded-md p-4 text-center">
                <p className="text-sm text-muted-foreground">
                  해당 기간에 추진경과가 없습니다.
                </p>
              </div>
            )}

          {/* 추가 옵션 */}
          <div className="space-y-3">
            <Label>추가 옵션</Label>
            <div className="space-y-2">
              <label className="flex items-center gap-2 cursor-pointer">
                <Checkbox
                  checked={includeNextPeriodPlans}
                  onCheckedChange={(checked) =>
                    setIncludeNextPeriodPlans(checked === true)
                  }
                />
                <span className="text-sm">
                  차주 계획 자동 반영 (상태=&apos;계획&apos;)
                </span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <Checkbox
                  checked={includeMeetings}
                  onCheckedChange={(checked) =>
                    setIncludeMeetings(checked === true)
                  }
                />
                <span className="text-sm">
                  회의/보고 유형 자동 포함
                </span>
              </label>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => {
              onOpenChange(false);
              resetState();
            }}
          >
            취소
          </Button>
          <Button
            type="button"
            onClick={handleGenerate}
            disabled={!canGenerate}
          >
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                생성 중...
              </>
            ) : (
              "생성"
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
