"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  FileText,
  Plus,
  ClipboardList,
  Filter,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { formatDate } from "@/lib/utils";
import type {
  ReportStatus,
} from "@/types/database";
import { AutoGenerateDialog } from "./auto-generate-dialog";

const statusConfig: Record<
  ReportStatus,
  { label: string; variant: "secondary" | "default" | "outline" }
> = {
  draft: { label: "작성중", variant: "secondary" },
  submitted: { label: "제출됨", variant: "default" },
  approved: { label: "승인됨", variant: "outline" },
};

interface ReportListProps {
  reports: Array<Record<string, unknown>>;
  templates: Array<Record<string, unknown>>;
  projects: Array<Record<string, unknown>>;
  currentMember: Record<string, unknown>;
}

export function ReportList({
  reports,
  templates,
  projects,
  currentMember,
}: ReportListProps) {
  const router = useRouter();
  const [projectFilter, setProjectFilter] = useState<string>("all");
  const [templateFilter, setTemplateFilter] = useState<string>("all");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [autoGenOpen, setAutoGenOpen] = useState(false);

  const filteredReports = useMemo(() => {
    return reports.filter((report) => {
      if (projectFilter !== "all" && report.project_id !== projectFilter)
        return false;
      if (templateFilter !== "all" && report.template_id !== templateFilter)
        return false;
      if (statusFilter !== "all" && report.status !== statusFilter)
        return false;
      return true;
    });
  }, [reports, projectFilter, templateFilter, statusFilter]);

  const handleGenerated = (reportId: string) => {
    setAutoGenOpen(false);
    router.push(`/reports/${reportId}`);
    router.refresh();
  };

  return (
    <>
      {/* Action Buttons */}
      <div className="flex flex-wrap gap-2">
        <Button onClick={() => setAutoGenOpen(true)}>
          <Plus className="h-4 w-4 mr-2" />
          보고서 자동 생성
        </Button>
        <Link href="/reports/progress">
          <Button variant="outline">
            <ClipboardList className="h-4 w-4 mr-2" />
            추진경과 관리
          </Button>
        </Link>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <Filter className="h-4 w-4 text-muted-foreground" />
        <Select value={projectFilter} onValueChange={setProjectFilter}>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="프로젝트" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">전체 프로젝트</SelectItem>
            {projects.map((p) => (
              <SelectItem key={p.id as string} value={p.id as string}>
                {(p.short_name as string) || (p.name as string)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <Select value={templateFilter} onValueChange={setTemplateFilter}>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="양식" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">전체 양식</SelectItem>
            {templates.map((t) => (
              <SelectItem key={t.id as string} value={t.id as string}>
                {t.name as string}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-[140px]">
            <SelectValue placeholder="상태" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">전체 상태</SelectItem>
            <SelectItem value="draft">작성중</SelectItem>
            <SelectItem value="submitted">제출됨</SelectItem>
            <SelectItem value="approved">승인됨</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Reports Table */}
      {filteredReports.length > 0 ? (
        <Card>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>제목</TableHead>
                  <TableHead>양식</TableHead>
                  <TableHead>프로젝트</TableHead>
                  <TableHead>기간</TableHead>
                  <TableHead>상태</TableHead>
                  <TableHead>생성일</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredReports.map((report) => {
                  const status = report.status as ReportStatus;
                  const config = statusConfig[status] || statusConfig.draft;
                  const template = report.report_templates as Record<
                    string,
                    unknown
                  > | null;
                  const project = report.projects as Record<
                    string,
                    unknown
                  > | null;

                  return (
                    <TableRow
                      key={report.id as string}
                      className="cursor-pointer"
                      onClick={() =>
                        router.push(`/reports/${report.id as string}`)
                      }
                    >
                      <TableCell className="font-medium">
                        {report.title as string}
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {template
                          ? (template.name as string)
                          : "-"}
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {project
                          ? (project.short_name as string) ||
                            (project.name as string)
                          : "-"}
                      </TableCell>
                      <TableCell className="text-muted-foreground text-sm">
                        {report.period_start as string} ~{" "}
                        {report.period_end as string}
                      </TableCell>
                      <TableCell>
                        <Badge variant={config.variant}>{config.label}</Badge>
                      </TableCell>
                      <TableCell className="text-muted-foreground text-sm">
                        {formatDate(report.created_at as string)}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16">
            <FileText className="h-12 w-12 text-muted-foreground mb-4" />
            <p className="text-lg font-medium">보고서가 없습니다</p>
            <p className="text-muted-foreground mt-1">
              새 보고서를 자동 생성하거나 추진경과를 먼저 등록하세요.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Auto Generate Dialog */}
      <AutoGenerateDialog
        open={autoGenOpen}
        onOpenChange={setAutoGenOpen}
        onGenerated={handleGenerated}
      />
    </>
  );
}
